name: Rust

on:
  pull_request:
    branches: [ master , main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev mingw-w64
    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy --verbose
